### ISSUE TITLE
Anti-Aliasing?

### ISSUE THREAD

**Issue by FireController1847** [codecentric/javafxsvg#13]
First off, I just want to say: I love this loader. Thanks for making it, it really makes working with SVG a breeze.

One thing I noticed is that when the SVG is drawn, it looks kind of pixellated. Is there any way to ensure anti-aliasing is applied and/or a more aggressive version? At the moment, this is what our logo currently looks like using your plugin:
![image](https://user-images.githubusercontent.com/16494272/72395552-2099e500-36f7-11ea-8214-2d9d638fdb8c.png)

Compared to what it looks like on, say, a browser:
![image](https://user-images.githubusercontent.com/16494272/72395649-6ce52500-36f7-11ea-8ed5-5a4dbb9f2401.png)

**Comment by 0x4a616e** [comment]
Maybe the issue is not with anti-aliasing but with the size of the image with which it is being rendered. Due to the design of javafx image rendering, `javafxsvg` _cannot_ anticipate the required imaged dimensions for whatever control it is rendered into. So `javafxsvg` _tries_ to take the size from the SVG tag or falls back to 400px i think... Then, _after_ the image is being rendered, JavaFX resizes the image again to the required dimensions. If this is the actual problem, you can fix it by either setting the appropriate dimensions directly in the SVG tag, or by using a custom `DimensionProvider` as hinted in the README. Does that help?

**Comment by FireController1847** [comment]
Yeah. I'm not sure what was going on. However, now that I've switched my project to JavaFX 11 & OpenJDK 11, I've decided to just simplify my life and use a PNG for the logo instead. If I had more SVG's to use I'd be more adamant about getting it to work, but seeing as it's just one logo, I'm not too bothered. Thanks! :)

**Comment by mipastgt** [comment]
@FireController1847 Just a side note: Why are you using the outdated JavaFX 11? The current version is 13 and you can use that with OpenJDK 11 without problem.

**Comment by FireController1847** [comment]
IDK just LTS really when the next LTS comes out I'll probably update to that
