### ISSUE TITLE
Blurry images

### ISSUE THREAD

**Issue by plata** [codecentric/javafxsvg#9]
I tried to use javafxsvg but the images are very blurry (see PlayOnLinux/POL-POM-5#597).

**Comment by 0x4a616e** [comment]
Hi! Sorry for the late reply, unfortunately i don't get notified when new issues are created.... do you by any chance still have a code sample for me to try this out? Is this on high dpi displays?

**Comment by plata** [comment]
I've tested this on a 2560x1440 monitor. As you can see in the linked pull request, the only thing I did is something like:
```Java
final String iconPath = "/icons/icon.svg";
Button testButton = new Button("Press");
testButton.setStyle("-fx-background-image: url('" + MyClass.class.getResource(iconPath).toExternalForm() + "');");
```

As I've described in the pull request, the issue might be related to some system dependent library installation.

If you have any idea what could cause this, I can try to add javafxsvg to our application again.

**Comment by 0x4a616e** [comment]
Is it possible that you use other styles to set the size of the background image, like `-fx-background-size: cover;`? I think the issue here is, that javafxsvg just cannot determine the actual size of the target svg to be displayed and thus falls back to a default size (wich is 400x400) for rendering and _then_, the image is scaled down by javafx in order to make it fit into the button making it look rather blurry.

Unfortunately, I don't really have a good solution to this because i don't think there is any means for javafxsvg to determine the size to the target element when embedding it as a css background image.

There _might_ however be a workaround: If the SVG has the correct size stored in attributes, this might be used by javafxsvg to render the image in the correct size. To use this, make sure you have `width` and `height` attribute defined in your svg and then enable svg support like this:

    		SvgImageLoaderFactory.install(new AttributeDimensionProvider());

Now, attributes from the svg will be used as the default size _if_ no size is explicitly requested by javafx (e.g. if you have an image control with a given size). You can also create your own dimension provider by implementing `DimensionProvider`. It'll always be used, when javafx does not request images in a specific size. I have no idea why javafx does not provide image dimensions when using css background images, even if `-fx-background-size` is set...

I hope this helps!

**Comment by plata** [comment]
The thing is that our GUI can be scaled (e.g. for UHD resolutions). This and the fact that we provide the image as part of a theme required us to set it as background image in CSS (at least we could not find a better solution). Therefore your analysis might very well be true.

I don't think we can store the size in the SVG attributes because we need different sizes depending on the GUI scaling.

While implementing a custom `DimensionProvider` could work, it seems a bit too complicated for the result (we currently use .png and those look nice).

So if this is something in javafx which you cannot work around, feel free to close the issue.
